services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    ports:
      - "5601:5601"

  tika:
    image: apache/tika:2.9.2.0
    command: -p 9998
    environment:
      - TIKA_OCR_ENABLED=true
      - TIKA_OCR_TIMEOUT=120000
      - TIKA_PDF_ocrStrategy=ocr_and_text
    ports:
      - "9998:9998"
    # Remarque: pour un OCR français fiable, utilisez une image Tika incluant Tesseract + fra.
    # Exemple alternatif: opensemanticsearch/tika

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
      - INDEX_NAME=ndf-docs
      - DOC_ROOT=/workspace/data/Note de frais
    depends_on:
      - opensearch
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace:ro

  ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    environment:
      - TIKA_URL=http://tika:9998
      - OPENSEARCH_URL=http://opensearch:9200
      - INDEX_NAME=ndf-docs
      - DOC_ROOT=/workspace/data/Note de frais
    depends_on:
      - opensearch
      - tika
    volumes:
      - ./:/workspace:ro

volumes:
  opensearch-data:


