FROM python:3.11-slim

WORKDIR /app

COPY requirements-api.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY api /app/api

ENV OPENSEARCH_URL=http://opensearch:9200
ENV INDEX_NAME=ndf-docs

EXPOSE 8080
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080"]


